import { type NextPage } from "next";
import Head from "next/head";
import Feed from "../components/Feed";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Explore the social app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed />
    </>
  );
};

export default Home;
